services:
  - type: web
    name: hyperliquid-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot_hyperliquid.py
    autoDeploy: true
